config/routes.rb
Rails.application.routes.draw do

 root 'home#home' 

 resources :contents 

 resources :contents do 
  resources :comments, only: [:create]  
 end

  resources :readers, only: [:update]
  resources :relationships, only: [:create, :destroy]

  resources :users, except: [:new] do
    member do
      get "send_message" 
    end
    collection do
      get "register_author"   
      post "register"
      get "register_reader"
    end
  end

  resources :users do 
    member do 
      get :following, :followers
  end
end 
 
  get '/login', to: "logins#new"
  post '/login', to: "logins#create"

  get '/logout', to: "logins#destroy"

  resources :categories, only: [:show]  

  resources :readers,  only:[:update]   
   
  resources :messages, only: [:create, :new, :index] 
 

end

app/models/content.rb
class Content < ActiveRecord::Base

	belongs_to :author 
	belongs_to :category
	has_many :comments   


	# validates :author_id, presence: true 
	validates :name, presence: true,length:{minimum: 5, maximum: 100}
	validates :description,presence: true,length:{minimum:15,maximum:500}

	mount_uploader :file, FileUploader

	def self.get_feeds(user_id) 
		ids = User.find(user_id).following.map { |user| user.author.id }
		Content.where("author_id in (?)", ids).order(:created_at)
	end
 
  
end 

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  
 before_action :set_content, only: [:edit,:update,:show,:destroy]
 before_action :require_user, except:[:show,:index] 
 before_action :require_same_user, only: [:edit,:update,:destroy]
 before_action :is_current_user_author, only: [:edit, :create, :new]



	def index 
    if current_user.is_author?
      @contents = Content.all.paginate(page: params[:page], per_page: 5)    
   else
		  @contents = Content.get_feeds(current_user.id).paginate(page: params[:page], per_page: 5) 
       if @contents.length==0
        @contents = Content.all.paginate(page: params[:page], per_page: 5) 
      end 
    end  
	end  
 
  
   

	def show  

	end	 


    def new
      @content = Content.new

      if unsigned_mode?
        @unsigned = true
        # make sure we have the appropriate preset
        @preset_name = "sample_" + Digest::SHA1.hexdigest(Cloudinary.config.api_key + Cloudinary.config.api_secret)
        begin                             
          preset = Cloudinary::Api.upload_preset(@preset_name)
          if !preset["settings"]["return_delete_token"]
            Cloudinary::Api.update_upload_preset(@preset_name, :return_delete_token=>true)
          end
        rescue
          # An upload preset may contain (almost) all parameters that are used in upload. The following is just for illustration purposes
          Cloudinary::Api.create_upload_preset(:name => @preset_name, :unsigned => true, :folder => "preset_folder", :return_delete_token=>true)
        end
      end

    end	


    def update
        if @content.update(content_params)
            flash[:success] = "Content Description has been updated succesfully"
            redirect_to content_path(@content) 
        else
            render :edit 
      end
    end	



# Creation form submission is handled by he create action 
    def create
        @content = Content.new(content_params)
        @content.author_id = current_user.author.id
        if @content.save 
            flash[:success] = "Your content is created successfully"
            redirect_to contents_path(@content) 
          else
            render:new 
       end     
    end	
 
   
  
   def edit 

   end


 
  def destroy 
    @content.destroy 
    redirect_to contents_path(@content)

  end   


  protected
  

  def direct_upload_mode?
    params[:direct].present?
  end
  

  def unsigned_mode?
    params[:unsigned].present?
  end
  

  def view_for_new
    direct_upload_mode? ? "new_direct" : "new"
  end

  
  private 

  def is_current_user_author
    if current_user && current_user.is_reader?
      redirect_to contents_path 
    end
  end

  def content_params
    params.require(:content).permit(:name,:description, :file, :category_id)
  end

  def set_content 
     @content = Content.find(params[:id]) 
  end 

  def require_same_user 
    if current_user != @content.author.user 
      flash[:danger] = "You can only edit your own content and create by Signing Up"
      redirect_to contents_path 
  end
 end  

 
end 

app/views/contents/edit.html.erb
<p>
	<h1>Edit content's description</h1>
   <hr/>
</p> 
  


 
<% if@content.errors.any? %>
 <div class="row">
 <div class="alert alert-danger col-md-8 col-md-offset-2">  
   <h5>Please correct the following errors:</h5>
   <ul>
     <% @content.errors.full_messages.each do |msg|%>
       <li><%= msg %></li> 
     <% end %> 
   </ul>
 </div>   
 </div>
<% end %> 
  



<div class="row">
<div class="well col-md-8 col-md-offset-2">
  <%= form_for @content, :class => "form-horizontal" do |f| %>

    <div class="form-group">
      <label class="col-lg-2 control-label">Name</label>
      <div class="col-lg-10">
        <%= f.text_field :name, :class => "form-control", :placeholder => "Name", :id => "Name" %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-lg-2 control-label">Description</label>
      <div class="col-lg-10">
        <%= f.text_area :description,cols: "20", rows: "5", :class => "form-control", :placeholder => "description", :id => "description" %>
      </div>
    </div>


    <div class="form-group">
      <label class="col-lg-2 control-label"></label>
      <div class="col-lg-10">    
        <br/>
    
        <%= f.submit 'Update description', class: "btn btn-success" %> 
      </div>
    </div>

    <% end %> 
	
</div>	
</div> 


































 

app/views/contents/index.html.erb
 <h1>All Contents</h1>


<%= will_paginate %> 

<% @contents.each do |content| %> 
<div class="row">
  <div class="col-md-1">

   <section class="chef_into center">
   	

    <div class="show_profile">
      <%= link_to ( image_tag(content.author.user.image.url, class:"gravatar", style: "height:60px;") ), user_path(content.author) if content.author.user.image %>     
      </div> 
      <p> 
        <%= link_to content.author.user.name, user_path(content.author) %> 
      </p>      
    </div>

    <div class="col-lg-8 well">  
    <h4><%= link_to content.name,content_path(content) %></h4>
    <P><%= content.description %></P>

    <%= link_to content.category.name,category_path(content.category) if content.category  %>  
    
    <p>
    <span class="quiet"><small><%= time_ago_in_words(content.created_at)%></small>
    </span>      
   </p>
  </div>

  </section>  
 


 </div> 
<% end %>

<%= will_paginate %> 
 


  

   

app/views/contents/new.html.erb
<p>
	<h1>Create a new content</h1>
   <hr/>
</p> 
  

<% if@content.errors.any? %>
 <div class="row">
 <div class="alert alert-danger col-md-8 col-md-offset-2">  
   <h5>Please correct the following errors:</h5>
   <ul>
     <% @content.errors.full_messages.each do |msg|%>
       <li><%= msg %></li> 
     <% end %> 
   </ul>
 </div>   
 </div>
<% end %> 
  



<div class="row">
<div class="well col-md-8 col-md-offset-2">
  <%= form_for @content, :class => "form-horizontal" do |f| %>

    <div class="form-group">
      <label class="col-lg-2 control-label">Name</label>
      <div class="col-lg-10">
        <%= f.text_field :name, :class => "form-control", :placeholder => "Name", :id => "Name" %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-lg-2 control-label">Description</label>
      <div class="col-lg-10">
        <%= f.text_area :description,cols: "20", rows: "5", :class => "form-control", :placeholder => "description", :id => "description" %>
      </div>
    </div>


    <div class="form-group">
      <label class="col-lg-2 control-label">Category</label>
      <div class="col-lg-10">
        <%= f.select :category_id, Category.all.collect {|c| [ c.name, c.id ] }, :prompt => 'Select One', :class => "form-control" %>
      </div>
    </div>


    <br/>

    <div class="form-group">
      <label class="col-lg-2 control-label"></label>
      <div class="col-lg-10">
        <%= f.file_field :file%>
      </div>
    </div>

    <br/>

    <%= f.submit 'Create Content', class: "btn btn-success" %> 


    <% end %> 
	
</div>	
</div>


































 

app/views/contents/show.html.erb
       
  <div class="row">

    <div class="col-md-8">
     <% if logged_in? %>
       <div class="btn-group pull-right" style="position:absolute; margin-left:830px">
          <a href="#" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to "Edit Description",edit_content_path(@content)%> 
            </li>
            <li>    
              <%= link_to "Delete Content", content_path(@content),method: :delete,
                data: { confirm: 'Are you sure?' }%> 
            </li>
            
            <li>
              <a href="<%= @content.file.url %>" role="button" >Full Screen</a>
            </li>
          </ul>
      </div>

      <div class="pull-right" style="position:absolute; margin-left:950px"> 
        <%= link_to image_tag(@content.author.user.image.url, style: "height:150px;"),user_path(@content.author)%>
        <p> <%= link_to @content.author.name, user_path(@content.author) %> </p>  
      </div>
        
      <% end %> 

     <h3><%= @content.name %></h3>
     <div class="well" style="width:885px">
       <%= @content.description %>
     </div>  

    <div class="well" style="width:885px" >
      <embed src="<%= @content.file.url(secure:true) %>" width="850" height="500" alt="pdf" pluginspage="https://www.adobe.com/products/acrobat/readstep2.html">   
    </div>

    </div>
    
  </div>
  
 <% if logged_in? %> 

<h4>Comments</h4>
<div>
   
  <%= form_for :comments, url: content_comments_path(@content, Comment.new), :class => "form-horizontal" do |f| %>

    <div class="form-group">
      <div class="col-lg-10">
        <%= f.text_area :body, cols: "20", rows: "2", :class => "form-control", :placeholder => "message", :id => "description" %>
      </div>
    </div>

    <%= f.submit "Add Comment", :class => "btn btn-primary" %>

  <% end %>
  
  </div>

  <% end %> 

 <div id="comments" style="margin-top:50px">
     <%= render :partial => @content.comments %>
  </div>

 








 
 