config/routes.rb
Rails.application.routes.draw do

 root 'home#home' 

 resources :contents 

 resources :contents do 
  resources :comments, only: [:create]  
 end

  resources :readers, only: [:update]
  resources :relationships, only: [:create, :destroy]

  resources :users, except: [:new] do
    member do
      get "send_message" 
    end
    collection do
      get "register_author"   
      post "register"
      get "register_reader"
    end
  end

  resources :users do 
    member do 
      get :following, :followers
  end
end 
 
  get '/login', to: "logins#new"
  post '/login', to: "logins#create"

  get '/logout', to: "logins#destroy"

  resources :categories, only: [:show]  

  resources :readers,  only:[:update]   
   
  resources :messages, only: [:create, :new, :index] 
 

end

app/models/user.rb
 class User < ActiveRecord::Base

has_one :author
has_one :reader  
has_many :comments   
has_many :messages

#This checks who you are following 
has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id"
          # ,dependent: :destroy
has_many :following, through: :active_relationships, source: :followed 
         
# This checks who is following you 
has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id"
          # ,dependent: :destroy 
has_many :followers, through: :passive_relationships, source: :follower

 
 
before_save {self.email = email.downcase}   

VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i 

validates :name, presence: true, length: {minimum: 3, maximum: 40 } 
validates :email, presence: true, length: {maximum:100} ,
										uniqueness: {case_sensitive: false},
										format: {with: VALID_EMAIL_REGEX}
# validates :image, presence: true
# validates :bytes, presence: true  

 

  validate :picture_size 

  mount_uploader :image, ImageUploader  

  
has_secure_password  

 def is_author?
 	self.author
 end

 def is_reader?
 	self.reader 
 end


 # You are following user
def follow(other)
 active_relationships.create(followed_id: other.id)
end

#unfollow a user
 def unfollow(other)
  	active_relationships.find_by(followed_id: other.id).destroy
 end  
  

  # checks whether you are following some user or not
 def following?(other)
   following.include?(other)
 end	
 
 

private
 def picture_size
 	if image.size > 5.megabytes
 		errors.add(:picture, "should be less than 5MB")
  end
 end  

 

end 	

app/controllers/users_controller.rb
 class UsersController < ApplicationController
  before_action :set_user ,only:[:edit,:update,:show]
	before_action :require_same_user, only: [:edit,:update] 
 
  def send_message
  end

  def new
    @user = User.new  

    if unsigned_mode?
        @unsigned = true
        # make sure we have the appropriate preset
        @preset_name = "sample_" + Digest::SHA1.hexdigest(Cloudinary.config.api_key + Cloudinary.config.api_secret)
        begin                             
          preset = Cloudinary::Api.upload_preset(@preset_name)
          if !preset["settings"]["return_delete_token"]
            Cloudinary::Api.update_upload_preset(@preset_name, :return_delete_token=>true)
          end
        rescue
          # An upload preset may contain (almost) all parameters that are used in upload. The following is just for illustration purposes
          Cloudinary::Api.create_upload_preset(:name => @preset_name, :unsigned => true, :folder => "preset_folder", :return_delete_token=>true)
        end
      end

  end


  def register_author
  	@user = User.new
  end


  def register_reader
 	@user = User.new
  end
 
 
   def register
  	@user = User.new(user_params)
  	if @user.save
  		if params[:user_type] == "author"
        flash[:success] = "Your author account has been created successfully"
  			Author.create(user_id: @user.id)
        session[:user_id] = @user.id 

  		else
      flash[:success] = "Your reader account has been created successfully"
  			Reader.create(user_id: @user.id)
        session[:user_id] = @user.id  
   
  		end
       redirect_to contents_path 
  	end    
  end


  def edit 

  end 

 
   def update 
    if @user.update(user_params)
      flash[:success] = "Your profile has beeem updated successfully"
      redirect_to user_path(@user)
    else   
      render 'edit' 
   end
   end
  

   def show 

   end
 
  
  def destroy
    @user = User.find_by_id(params[:id])
    if @user.destroy
      session[:user_id] = nil
      redirect_to root_url, notice: "User deleted."
    end
  end
 
   
 
 

  def index
   @users = User.all 
  end

  private 
  def user_params
  	params.require(:user).permit(:email, :name, :password, :image)
  end
 

  def set_user
    @user = User.find(params[:id])
  end  


  def require_same_user
   if current_user != @user
    flash[:danger] = "You can edit your own profile"
    redirect_to register_author_users_path 
  end
 end
 


 

 

 end 

app/views/users/_form.html.erb
  <%= render 'shared/errors',obj:@user %>

 
<% if @user.errors.any? %>
 <div class="row">
 <div class="alert alert-danger col-md-offset-2"> 
   <h5>Please correct the following errors:</h5>
   <ul>
     <% @user.errors.full_messages.each do |msg|%>
       <li><%= msg %></li> 
     <% end %> 
   </ul>
 </div>   
 </div>
<% end %>  


 
<div class="row">
	<div class="well col-md-8 col-md-offset-2">

	<%= form_for @user, :class => "form-horizontal" do |f| %> 
		<fieldset>

			<div class="form-group">
		      <label for="inputEmail" class="col-lg-2 control-label">Name</label>
		      <div class="col-lg-10">
				<%= f.text_field :name, :class => "form-control", :placeholder => "Name", :id => "Name" %>
		      </div>
		    </div>

		    <div class="form-group">
		      <label for="inputEmail" class="col-lg-2 control-label">Email</label>
		      <div class="col-lg-10">
				<%= f.text_field :email, :class => "form-control", :placeholder => "Email", :id => "Email" %>
		      </div>
		    </div>

		    
		    <div class="form-group">
		      <label for="inputPassword" class="col-lg-2 control-label">Password</label>
		      <div class="col-lg-10">
		      	<%= f.password_field :password, :class => "form-control", :id => "inputPassword", :placeholder => "Password" %>
		      </div>
		    </div>

		    <div class="form-group">
		    	<div class="col-lg-10 col-lg-offset-2">
		    		<br>
					<%= f.submit(@user.new_record? ? 'Register' : 'Update',class:"btn btn-success") %>  
	            </div>
	        </div>

	  	</fieldset>
	<% end %>   
	</div>  
</div> 

app/views/users/edit.html.erb
<%= render 'shared/page_title',title: "Update Profile " %>   
<%= render 'form' %> 


<div class="row">
	<div class="well col-md-8 col-md-offset-2"> 

<%if current_user.is_reader? %>
	<%= form_for current_user.reader  do |f| %>
		
	<div class="form-group">
		<label for="inputEmail" class="col-lg-2 control-label">Category</label>
      <div class="col-lg-10">
		<%= f.select :interest, Category.all.collect {|c| [ c.name, c.id ] }, :prompt => 'Select One' %>
      </div>




      		<div class="form-group">
		    	<div class="col-lg-10 col-lg-offset-2">
		    		<br>
					<%= f.submit('Update category',class:"btn btn-success") %>  
	            </div>
	        </div>

    

  
	<% end %> 


<% end %>

</div>
</div>

app/views/users/new.html.erb
<%= render 'shared/page_title',title: "Create A New User" %>   


<%= render 'form' %> 

  



    
 

app/views/users/register_author.html.erb
  <%= render 'shared/page_title',title: "Register as Author" %>   

 

  <%= render 'shared/errors',obj:@user %>
 
  
 
<div class="row">
	<div class="well col-md-8 col-md-offset-2"> 
<%= form_for @user, url:register_users_path do |f| %>

		<fieldset>

			<div class="form-group">
		      <label for="inputEmail" class="col-lg-2 control-label">Name</label>
		      <div class="col-lg-10">
				<%= f.text_field :name, :class => "form-control", :placeholder => "Name", :id => "Name" %>
		      </div>
		    </div>

		    <div class="form-group">
		      <label for="inputEmail" class="col-lg-2 control-label">Email</label>
		      <div class="col-lg-10">
				<%= f.text_field :email, :class => "form-control", :placeholder => "Email", :id => "Email" %>
		      </div>
		    </div>

		    
		    <div class="form-group">
		      <label for="inputPassword" class="col-lg-2 control-label">Password</label>
		      <div class="col-lg-10">
		      	<%= f.password_field :password, :class => "form-control", :id => "inputPassword", :placeholder => "Password" %>
		      </div>
		    </div>


		    <div class="form-group">
		      <label for="inputPassword" class="col-lg-2 control-label"></label>
		      <div class="col-lg-10">
		      	<%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png'%>
		      </div>
		    </div>


		    <div class="form-group">
		    	<div class="col-lg-10 col-lg-offset-2">
		    		<br>
					<%= f.submit(@user.new_record? ? 'Register' : 'Update',class:"btn btn-success") %>  
	            </div>
	        </div>

	  	</fieldset>


		<input type="hidden" name="user_type" value="author">

		<% end %>   
	</div>  
</div> 


 
<script type="text/javascript">
    $('#user_picture').bind('change',function(){
	size_in_megabytes = this.files[0].size/1024/1024;
	if(size_in_megabytes > 5 ){
		alert("Maximum file is 5MB.Please choose a smaller file");
	}
    });
</script>



 

app/views/users/register_reader.html.erb
  <%= render 'shared/page_title',title: "Register as reader" %>   


  <%= render 'shared/errors',obj:@user %>

 
 
<div class="row">
	<div class="well col-md-8 col-md-offset-2"> 
		<%= form_for @user, url: register_users_path do |f| %> 


		<fieldset>

			<div class="form-group">
		      <label for="inputEmail" class="col-lg-2 control-label">Name</label>
		      <div class="col-lg-10">
				<%= f.text_field :name, :class => "form-control", :placeholder => "Name", :id => "Name" %>
		      </div>
		    </div>

		    <div class="form-group">
		      <label for="inputEmail" class="col-lg-2 control-label">Email</label>
		      <div class="col-lg-10">
				<%= f.text_field :email, :class => "form-control", :placeholder => "Email", :id => "Email" %>
		      </div>
		    </div>

		    
		    <div class="form-group">
		      <label for="inputPassword" class="col-lg-2 control-label">Password</label>
		      <div class="col-lg-10">
		      	<%= f.password_field :password, :class => "form-control", :id => "inputPassword", :placeholder => "Password" %>
		      </div>
		    </div>


		    <div class="form-group">
		      <label for="inputPassword" class="col-lg-2 control-label"></label>
		      <div class="col-lg-10">
		      	<%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png'%>
		      </div>
		    </div>


		    <div class="form-group">
		    	<div class="col-lg-10 col-lg-offset-2">
		    		<br>
					<%= f.submit(@user.new_record? ? 'Register' : 'Update',class:"btn btn-success") %>  
	            </div>
	        </div>

	  	</fieldset>





		<input type="hidden" name="user_type" value="reader">
    
		<% end %>   
	</div>  
</div> 

 

app/views/users/send_message.html.erb
<div id="stream">
	<%= form_for :message, url: messages_path do |f| %>
		<%= f.text_area :body, id: "url", placeholder: "Message", class: "message-body"%>
		<input name="message[recipient_id]" type="hidden" value="<%= params[:id]%>">
	
	<div id ="stream-footer"> 
 		<%= f.button :submit, class: "btn btn-outline"%>
 	</div>
 	<% end %>
 </div>

app/views/users/show.html.erb
  <%= render 'shared/page_title',title: @user.name %>  


	<div class="col-md-4 pull-left center">  
		<div class="show_profile">
      <%= image_tag(@user.image.url, class:"gravatar") if @user.image? %> 
      </div>
   <%if @user.is_author?  %>

   <div class="col-sm-6" style="font-size:80%; opacity:0.7;">Followers<br>
    <h6><%=@user.followers.count %></h6>

   <%= render '/followings/follow_button', :user => @user%>   
  <% end %>


<% if current_user.is_reader? %> 
 <div class="col-sm-6" style="font-size:80%; opacity:0.7;">Following<br>
   <h6><%=@user.following.count %></h6>
 </div>
 <% end %> 


  </div>


    </div>

     
 


  
 
  

   
 <% if logged_in? %> 
    <%= link_to "Send Message", send_message_user_path(@user), class: "btn btn-success pull-right"%> 
      <% end %> 




<%if @user.is_author?  %>
   <div class="indexcontent"> 
    <% @user.author.contents.each do |content| %>  
      <div class="row"> 
        <div class="col-lg-6 well col-lg-offset-3"> 
        	<h4><%= link_to content.name,content_path(content) %></h4>
        	<p><%= link_to content.description %></p> 
          <p>
          	<span class="quiet">
              <small> 
                created: <%= time_ago_in_words(content.created_at)%> ago, 
              </small>
            </span>

          	<span class="quiet">
              <small> 
                created: <%= time_ago_in_words(content.created_at)%> ago, 
              </small>
            </span>
          </p>
        </div> 
      </div> 
    <% end %>
  </div>
<% end %>



<% if current_user.is_reader? %>
  <%= link_to current_user.reader.show_interest.name, category_path(current_user.reader.show_interest) if current_user.reader.show_interest %> 
<% end %> 
   
   
 
 