config/routes.rb
Rails.application.routes.draw do

 root 'home#home' 

 resources :contents 

 resources :contents do 
  resources :comments, only: [:create]  
 end

  resources :readers, only: [:update]
  resources :relationships, only: [:create, :destroy]

  resources :users, except: [:new] do
    member do
      get "send_message" 
    end
    collection do
      get "register_author"   
      post "register"
      get "register_reader"
    end
  end

  resources :users do 
    member do 
      get :following, :followers
  end
end 
 
  get '/login', to: "logins#new"
  post '/login', to: "logins#create"

  get '/logout', to: "logins#destroy"

  resources :categories, only: [:show]  

  resources :readers,  only:[:update]   
   
  resources :messages, only: [:create, :new, :index] 
 

end

app/views/layouts/_messages.html.erb
 <div class="row">
 	<div class="col-md-8 col-md-offset-2">
 		<% flash.each do |message_type, message|%>
 		<div class="alert alert-" <%= message_type %>> <%= message %> 
 			<a class="close" data-dismiss="alert"> &#215; </a>
 		</div>
 		<% end %> 
 	</div> 
 </div>

app/views/layouts/_navigation.html.erb
<% if logged_in? %>

  <ul class="nav navbar-nav navbar-right">
  <li class="dropdown">  
  <%= link_to '#', class: "dropdown-toggle",
  'data-toggle' => "dropdown" do %>  
   
   <%= current_user.name %> <b class="caret"></b> 
   <% end %>
   <ul class="dropdown-menu">  
    <li> <%= link_to "View Profile", user_path(current_user)%></li>
    <li><%= link_to  "Edit Profile", edit_user_path(current_user)%></li>

     <% if current_user.is_reader? %>
        <li> <%= link_to "Recommended Content", category_path(current_user.reader.show_interest) if current_user.reader.show_interest %> </li>
     <% end %> 


    <% if(current_user.is_author?) %>   
      <li><%= link_to  "Create Content", new_content_path%></li> 
    <% end %>

    <li><%= link_to  "Inbox", messages_path%></li> 


    <li class="divider"></li>
    <li> <%= link_to "Delete Account", current_user,       
              method: :delete,
              data: { confirm: 'Are you sure?' } %> </li>  

     <li><%= link_to "Logout", logout_path %></li>           
   </ul>  
  </li>  
 </ul>

<% else %>
  <ul class="nav navbar-nav navbar-right">
    <li>
      <%= link_to "Login", login_path %>  
    </li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Authorapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "Content App", root_path, class: "navbar-brand", id: "logo" %>
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar-main">
		<%= render 'layouts/navigation' %> 
    </div>
  </div>
</div>

<div class="container" style="margin-top:100px">

	<%= render 'layouts/messages'%> 
	<%= yield %>
</div>



</body>
</html>